### ISSUE TITLE
未能加载文件或程序集“System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。

### ISSUE THREAD

**Issue by colindcli** [colindcli/CodeGit#31]
[FileNotFoundException: 未能加载文件或程序集“System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。]
       System.Web.Http.GlobalConfiguration..cctor() +0
    
    [TypeInitializationException: “System.Web.Http.GlobalConfiguration”的类型初始值设定项引发异常。]
       System.Web.Http.GlobalConfiguration.get_Configuration() +24
       Ourtm.WebApiPc.SwaggerConfig.Register() in \App_Start\SwaggerConfig.cs:18
    
    [TargetInvocationException: 调用的目标发生了异常。]
       System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
       System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +260
       System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
       WebActivatorEx.BaseActivationMethodAttribute.InvokeMethod() +83
       WebActivatorEx.ActivationManager.RunActivationMethods(Boolean designerMode) +699
       WebActivatorEx.ActivationManager.Run() +125
    
    [InvalidOperationException: 针对类型 WebActivatorEx.ActivationManager 的应用程序预启动初始化方法 Run 引发了异常，显示下列错误消息: 调用的目标发生了异常。。]
       System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +904
       System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +169
       System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +173
       System.Web.Compilation.BuildManager.ExecutePreAppStart() +172
       System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +912
    
    [HttpException (0x80004005): 针对类型 WebActivatorEx.ActivationManager 的应用程序预启动初始化方法 Run 引发了异常，显示下列错误消息: 调用的目标发生了异常。。]
       System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +534
       System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +117
       System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +726

**Comment by colindcli** [comment]
https://www.nuget.org/packages/System.Net.Http/
安装System.Net.Http解决

**Comment by passengerJIA** [comment]
安装以后也没有解决这个问题
